name: Publish docs

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libkrb5-dev
      - name: Install Tox
        run: pip install tox 'virtualenv<20.21.1'
      - name: Run Tox
        run: tox -e docs
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs/_build/html
